Library Project/Models/DocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Library_Project.Models
{
    public class DocumentViewModel
    {

        public int Id { get; set; }
        [Required]
        [DisplayName("नाम")]
        public string Name { get; set; }
        [Required]
        [DisplayName("वर्ग")]

        public int Category_Id { get; set; }
        [DisplayName("वर्ग")]

        public string Category_Name { get; set; }
        [Required]
        [DisplayName("अप-वर्ग ")]

        public int Sub_Category_Id { get; set; }
        [DisplayName("अप-वर्ग ")]

        public string Sub_Category_Name { get; set; }
        [Required]
        [DisplayName("कागजातको स्रोत ")]

        public int Document_Source_Id { get; set; }
        [DisplayName("कागजातको स्रोत ")]

        public string Document_Source_Name { get; set; }
        [Required]
        [DisplayName("आर्थिक बर्ष ")]

        public int Fiscal_Year_Id { get; set; }

        [DisplayName("आर्थिक बर्ष ")]
        public string Fiscal_Year_Name { get; set; }
        [Required]
        [DisplayName("प्रदेश")]

        public int State_Id { get; set; }
        [DisplayName("प्रदेश")]
        public string State_Name { get; set; }
        [Required]
        [DisplayName("जिल्ला")]

        public int District_Id { get; set; }

        [DisplayName("जिल्ला")]
        public string District_Name { get; set; }
        [Required]
        [DisplayName("पालिका")]

        public int Palika_Id { get; set; }

        [DisplayName("पालिका")]
        public string Palika_Name { get; set; }
        [Required]
        [DisplayName("कागजातको प्रकार ")]

        public int Document_Type_Id { get; set; }
        [DisplayName("कागजातको प्रकार ")]
        public string Document_Type_Name { get; set; }


        public List<DocumentFileModel> ImageFile { get; set; } = new List<DocumentFileModel>();
    }
}

Library Project/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Project.Controllers
{
    public class AjaxController : Controller
    {

            DLMSDatabaseEntities context = new DLMSDatabaseEntities();
            public JsonResult District(int Sid)
            {

                var result = context.District.Where(x => x.State_Id == Sid).ToList();

                var selectList = new SelectList(result, "Id", "Name")
    ;
                return Json(selectList, JsonRequestBehavior.AllowGet);

            }

            public JsonResult Palika(int Pid)
            {

                var result = context.Palika.Where(x => x.District_Id == Pid).ToList();

                var selectList = new SelectList(result, "Id", "Name")
    ;
                return Json(selectList, JsonRequestBehavior.AllowGet);

            }

            public JsonResult SubCategoryAjax(int Scid)
            {

                var result = context.Sub_Category.Where(x => x.Category_Id == Scid).ToList();

                var selectList = new SelectList(result, "Id", "Name")
    ;
                return Json(selectList, JsonRequestBehavior.AllowGet);

            }
            
        }
    }

Library Project/Controllers/DocumentController.cs
using Library_Project.Interface;
using Library_Project.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Project.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        private readonly IDocument _document;
        public DocumentController(IDocument document)
        {
            _document = document;
        }
        public ActionResult Create()
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.ToList(), "Id", "Name");
                ViewBag.SubCategoryList = new SelectList(con.Sub_Category.ToList(), "Id", "Name");
                ViewBag.DocumentSource = new SelectList(con.Document_Source.ToList(), "Id", "Name");
                ViewBag.FiscalYear = new SelectList(con.Fiscal_Year.ToList(), "Id", "Name");
                ViewBag.StateList = new SelectList(con.State.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(con.District.ToList(), "Id", "Name");
                ViewBag.PalikaList = new SelectList(con.Palika.ToList(), "Id", "Name");
                ViewBag.DocumentType = new SelectList(con.Document_Type.ToList(), "Id", "Name");



            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(DocumentViewModel model)
        {
            int id = _document.AddDocument(model);
            if (id > 0)
            {
                ModelState.Clear();
                ViewBag.IsSuccess = "Data Added";
                foreach (var item in model.ImageFile)
                {
                    var imagePath = "/File/";


                    using (var con = new DLMSDatabaseEntities())
                    {
                        if ( item!= null)
                        {


                            var fileName = Path.GetFileName(item.ImageFiles.FileName);
                            var path = Path.Combine(Server.MapPath(imagePath), fileName);
                            //item..SaveAs(path);
                            item.ImageFiles.SaveAs(path);    
                            item.File_Path = imagePath + item.Name;
                            Document_File document_File = new Document_File()
                            {
                                File_Path = item.File_Path,
                                Name = fileName,
                            };
                            con.Document_File.Add(document_File);
                            con.SaveChanges();
                        }

                    }
                }
                return RedirectToAction("GetAllRecords");

            }

            return View(model);
        }

        public ActionResult GetAllRecords()
        {
            var result = _document.GetAllDocuments();
            return View(result);
        }

        public ActionResult Details(int id)
        {
            var doc = _document.GetDocument(id);
            return View(doc);
        }

        public ActionResult Edit(int id)
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.ToList(), "Id", "Name");
                ViewBag.SubCategoryList = new SelectList(con.Sub_Category.ToList(), "Id", "Name");
                ViewBag.DocumentSource = new SelectList(con.Document_Source.ToList(), "Id", "Name");
                ViewBag.FiscalYear = new SelectList(con.Fiscal_Year.ToList(), "Id", "Name");
                ViewBag.StateList = new SelectList(con.State.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(con.District.ToList(), "Id", "Name");
                ViewBag.PalikaList = new SelectList(con.Palika.ToList(), "Id", "Name");
                ViewBag.DocumentType = new SelectList(con.Document_Type.ToList(), "Id", "Name");


            }
            var doc = _document.GetDocument(id);
            return View(doc);
        }


        [HttpPost]
        public ActionResult Edit(DocumentViewModel model)
        {
            if (ModelState.IsValid)
            {
                _document.UpdateDocument(model.Id, model);

                return RedirectToAction("GetAllRecords");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            _document.DeleteDocument(id);
            return RedirectToAction("GetAllRecords");
        }

        [HttpPost]
        public ActionResult Upload(DocumentFileModel model)
        {

            var imagePath = "/File/";

            using (var con = new DLMSDatabaseEntities())
            {
                if (model.ImageFiles != null)
                {


                    var fileName = Path.GetFileName(model.ImageFiles.FileName);
                    var path = Path.Combine(Server.MapPath(imagePath), fileName);
                    model.ImageFiles.SaveAs(path);
                    model.File_Path = imagePath + model.ImageFiles.FileName;
                    Document_File document_File = new Document_File()
                    {
                        File_Path = model.File_Path,
                        Name = fileName,
                    };
                    con.Document_File.Add(document_File);
                    con.SaveChanges();
                }
            }
            return View();
        }
        public PartialViewResult Index()
        {
            return PartialView("_image", new DocumentFileModel());
        }
    }
}

Library Project/Views/Document/Create.cshtml
@model Library_Project.Models.DocumentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>नया थप्नुहोस </h2>

@using (Html.BeginForm("Create", "Document", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>@ViewBag.IsSuccess</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_Id, ViewBag.CategoryList as SelectList, "-- छान्नुहोस् -- ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sub_Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Sub_Category_Id, ViewBag.SubCategoryList as SelectList, "-- छान्नुहोस् -- ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sub_Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Document_Source_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Document_Source_Id, ViewBag.DocumentSource as SelectList, "-- छान्नुहोस्  --  ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document_Source_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiscal_Year_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Fiscal_Year_Id, ViewBag.FiscalYear as SelectList, "-- छान्नुहोस्  -- ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Fiscal_Year_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (ViewBag.StateList != null)
                {
                    @Html.DropDownListFor(model => model.State_Id, ViewBag.StateList as SelectList, "-- प्रदेश--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.State_Id, "", new { @class = "text-danger" })

                }

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.District_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.District_Id, ViewBag.DistrictList as SelectList, "-- जिल्ला --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.District_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Palika_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Palika_Id, ViewBag.PalikaList as SelectList, "-- पालिका --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Palika_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Document_Type_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Document_Type_Id, ViewBag.DocumentType as SelectList, "-- छान्नुहोस् --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document_Type_Id, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div id="test">
        @Html.Partial("_image", new Library_Project.Models.DocumentFileModel())

    </div>
    <div class="col-md-offset-2 col-md-1 ">
        <button class="btn btn-primary" type="button" id="addPartial" onclick="abc()">
            <i class="fa-solid fa-file-circle-plus"></i> Add
        </button>
    </div>
    <div class="row" style="margin-top:18px">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" value="Create" class="btn btn-outline-primary" />
        </div>
    </div>
}
<div>
    @Html.ActionLink("पछाडी जानुहोस ", "Index", "Home")
</div>
@section Scripts{

    <script>
        $(document).ready(function () {
            $("#State_Id").change(function () {
                var selectedCountryId = $(this).val();
                $.ajax({
                    url: "@Url.Action("District", "Ajax")",
                    type: "GET",
                    data: { Sid: selectedCountryId },
                    success: function (data) {
                        $("#District_Id").empty();
                        $("#District_Id").append('<option value="">Select District</option>');
                        $.each(data, function (index, district) {
                            $("#District_Id").append('<option value="' + district.Value + '">' + district.Text + '</option>');
                        });
                    }
                });


            });
            $("#District_Id").change(function () {
                var selectedDistrictId = $(this).val();
                $.ajax({
                    url: "@Url.Action("Palika", "Ajax")",
                    type: "GET",
                    data: { Pid: selectedDistrictId },
                    success: function (data) {
                        $("#Palika_Id").empty();
                        $("#Palika_Id").append('<option value="">Select Palika</option>');
                        $.each(data, function (index, palika) {
                            $("#Palika_Id").append('<option value="' + palika.Value + '">' + palika.Text + '</option>');
                        });
                    }

                });
            });

            $("#Category_Id").change(function () {
                var selectedCategoryId = $(this).val();
                $.ajax({
                    url: "@Url.Action("SubCategoryAjax", "Ajax")",
                    type: "GET",
                    data: { Scid: selectedCategoryId },
                    success: function (data) {
                        $("#Sub_Category_Id").empty();
                        $("#Sub_Category_Id").append('<option value="">Select Sub_Category</option>');
                        $.each(data, function (index, subcategory) {
                            $("#Sub_Category_Id").append('<option value="' + subcategory.Value + '">' + subcategory.Text + '</option>');
                        });
                    }

                });
            });

        });

        function abc() {
            $.ajax({
                url: "@Url.Action("Index", "Document")",
                success: (function (data)
                {
                    var ran = $('#test').append(data);
                })
            })
        }

    </script>
}

Library Project/Views/Document/Delete.cshtml
@model Library_Project.Models.DocumentViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>हटाउनुहोस्</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sub_Category_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sub_Category_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sub_Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sub_Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Document_Source_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Source_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Document_Source_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Source_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiscal_Year_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiscal_Year_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiscal_Year_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiscal_Year_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.District_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.District_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.District_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.District_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Palika_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Palika_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Palika_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Palika_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Document_Type_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Type_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Document_Type_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Type_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="हटाउनुहोस्" class="btn btn-default" />
    @Html.ActionLink("पछाडी जानुहोस ", "getallrecords")
</div>
    }
</div>

Library Project/Views/Document/Details.cshtml
@model Library_Project.Models.DocumentViewModel

@{
    ViewBag.Title = "Details";
}

<h2>पुरा विवरण </h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sub_Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sub_Category_Name)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Document_Source_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Source_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiscal_Year_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiscal_Year_Name)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.State_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State_Name)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.District_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.District_Name)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Palika_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Palika_Name)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Document_Type_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Type_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("सम्पादन", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("पछाडी जानुहोस ", "getallrecords")
</p>

Library Project/Views/Document/Edit.cshtml
@model Library_Project.Models.DocumentViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>सम्पादन गर्नुहोस </h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>@ViewBag.IsSuccess</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_Id, ViewBag.CategoryList as SelectList, "-- छान्नुहोस् --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sub_Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Sub_Category_Id, ViewBag.SubCategoryList as SelectList, "-- छान्नुहोस् -- ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sub_Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Document_Source_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Document_Source_Id, ViewBag.DocumentSource as SelectList, "-- छान्नुहोस् --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document_Source_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiscal_Year_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Fiscal_Year_Id, ViewBag.FiscalYear as SelectList, "-- छान्नुहोस् --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Fiscal_Year_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (ViewBag.StateList != null)
                {
                    @Html.DropDownListFor(model => model.State_Id, ViewBag.StateList as SelectList, "--प्रदेश छान्नुहोस् --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.State_Id, "", new { @class = "text-danger" })

                }

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.District_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.District_Id, ViewBag.DistrictList as SelectList, "--जिल्ला छान्नुहोस् --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.District_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Palika_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Palika_Id, ViewBag.PalikaList as SelectList, " -- पालिका छान्नुहोस् --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Palika_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Document_Type_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Document_Type_Id, ViewBag.DocumentType as SelectList, "-- छान्नुहोस् --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document_Type_Id, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    @Html.Partial("_image", new Library_Project.Models.DocumentFileModel())
    <div class="col-md-offset-2 col-md-1 ">
        <a class="btn btn-primary" >
            <i class="fa-solid fa-file-circle-plus"></i> Add </a>
    </div>
        <div class="row" style="margin-top:20px">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("पछाडी जानुहोस ", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library Project/Views/Document/GetAllRecords.cshtml
@model IEnumerable<Library_Project.Models.DocumentViewModel>

@{
    ViewBag.Title = "GetAllRecords";
}


<p>
    <a class="btn btn-outline-primary" href="@Url.Action("Create")">नया थप्नुहोस</a>
</p>
<table id="example" class="table table-hover" style="width:100%">
    <thead class="table-dark ">
        <tr>
            <th>क.स</th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sub_Category_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Document_Source_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fiscal_Year_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.District_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Palika_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Document_Type_Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@(Model.ToList().IndexOf(item)+1)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sub_Category_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Document_Source_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fiscal_Year_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.District_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Palika_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Document_Type_Name)
                </td>
                <td>
                    <i class='fas fa-pencil-alt'></i> @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "action - link" }) |
                    <i class='fas fa-info-circle'></i> @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "action-link" }) |
                    <i class='fas fa-trash'></i> @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "action-link" }) |

                </td>
            </tr>
        }
    </tbody>
</table>