Library Project/Controllers/CategoryController.cs
using Library_Project.Interface;
using Library_Project.Models;
using Library_Project.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Project.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategory _category;
        public CategoryController(ICategory category)
        {
            _category = category;
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                int id = _category.AddCategory(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.IsSuccess = "Data Added";
                    return RedirectToAction("getallrecords");
                   
                }
            }
            return View(model);
        }

        public ActionResult GetAllRecords()
        {
            var result = _category.GetAllCategories();
            return View(result);
        }

        public ActionResult Details(int id)
        {
            var category = _category.GetCategory(id);
            return View(category);
        }

        public ActionResult Edit(int id)
        {
            var category = _category.GetCategory(id);
            return View(category);
        }


        [HttpPost]
        public ActionResult Edit(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                _category.UpdateCategory(model.Id, model);

                return RedirectToAction("GetAllRecords");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            _category.DeleteCategory(id);
            return RedirectToAction("GetAllRecords");
        }


    }
}

Library Project/Controllers/DocumentController.cs
using Library_Project.Interface;
using Library_Project.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Project.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        private readonly IDocument _document;
        public DocumentController(IDocument document)
        {
            _document = document;
        }
        public ActionResult Create()
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.ToList(), "Id", "Name");
                ViewBag.SubCategoryList = new SelectList(con.Sub_Category.ToList(), "Id", "Name");
                ViewBag.DocumentSource = new SelectList(con.Document_Source.ToList(), "Id", "Name");
                ViewBag.FiscalYear = new SelectList(con.Fiscal_Year.ToList(), "Id", "Name");
                ViewBag.StateList = new SelectList(con.State.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(con.District.ToList(), "Id", "Name");
                ViewBag.PalikaList = new SelectList(con.Palika.ToList(), "Id", "Name");
                ViewBag.DocumentType = new SelectList(con.Document_Type.ToList(), "Id", "Name");



            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(DocumentViewModel model)
        {
            int id = _document.AddDocument(model);
            if (id > 0)
            {
                ModelState.Clear();
                ViewBag.IsSuccess = "Data Added";
                foreach (var item in model.ImageFile)
                {
                    var imagePath = "/File/";


                    using (var con = new DLMSDatabaseEntities())
                    {
                        if ( item!= null)
                        {


                            var fileName = Path.GetFileName(item.ImageFiles.FileName);
                            var path = Path.Combine(Server.MapPath(imagePath), fileName);
                            //item..SaveAs(path);
                            item.ImageFiles.SaveAs(path);    
                            item.File_Path = imagePath + item.Name;
                            Document_File document_File = new Document_File()
                            {
                                File_Path = item.File_Path,
                                Name = fileName,
                            };
                            con.Document_File.Add(document_File);
                            con.SaveChanges();
                        }

                    }
                }
                return RedirectToAction("GetAllRecords");

            }

            return View(model);
        }

        public ActionResult GetAllRecords()
        {
            var result = _document.GetAllDocuments();
            return View(result);
        }

        public ActionResult Details(int id)
        {
            var doc = _document.GetDocument(id);
            return View(doc);
        }

        public ActionResult Edit(int id)
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.ToList(), "Id", "Name");
                ViewBag.SubCategoryList = new SelectList(con.Sub_Category.ToList(), "Id", "Name");
                ViewBag.DocumentSource = new SelectList(con.Document_Source.ToList(), "Id", "Name");
                ViewBag.FiscalYear = new SelectList(con.Fiscal_Year.ToList(), "Id", "Name");
                ViewBag.StateList = new SelectList(con.State.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(con.District.ToList(), "Id", "Name");
                ViewBag.PalikaList = new SelectList(con.Palika.ToList(), "Id", "Name");
                ViewBag.DocumentType = new SelectList(con.Document_Type.ToList(), "Id", "Name");


            }
            var doc = _document.GetDocument(id);
            return View(doc);
        }


        [HttpPost]
        public ActionResult Edit(DocumentViewModel model)
        {
            if (ModelState.IsValid)
            {
                _document.UpdateDocument(model.Id, model);

                return RedirectToAction("GetAllRecords");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            _document.DeleteDocument(id);
            return RedirectToAction("GetAllRecords");
        }

        [HttpPost]
        public ActionResult Upload(DocumentFileModel model)
        {

            var imagePath = "/File/";

            using (var con = new DLMSDatabaseEntities())
            {
                if (model.ImageFiles != null)
                {


                    var fileName = Path.GetFileName(model.ImageFiles.FileName);
                    var path = Path.Combine(Server.MapPath(imagePath), fileName);
                    model.ImageFiles.SaveAs(path);
                    model.File_Path = imagePath + model.ImageFiles.FileName;
                    Document_File document_File = new Document_File()
                    {
                        File_Path = model.File_Path,
                        Name = fileName,
                    };
                    con.Document_File.Add(document_File);
                    con.SaveChanges();
                }
            }
            return View();
        }
        public PartialViewResult Index()
        {
            return PartialView("_image", new DocumentFileModel());
        }
    }
}

Library Project/Controllers/FiscalYearController.cs
using Library_Project.Interface;
using Library_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Project.Controllers
{
    [Authorize]
    public class FiscalYearController : Controller
    {
        private readonly IFiscalYear _fiscalyear;
        public FiscalYearController(IFiscalYear fiscalYear)
        {
            _fiscalyear = fiscalYear;
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FiscalYearViewModel model)
        {
            if (ModelState.IsValid)
            {
                int id = _fiscalyear.AddFiscalYear(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.IsSuccess = "Data Added";
                    return RedirectToAction("getallrecords");
                }
            }
            return View(model);
        }

        public ActionResult GetAllRecords()
        {
            var result = _fiscalyear.GetAllFiscalYear();
            return View(result);
        }

        public ActionResult Details(int id)
        {
            var fiscal = _fiscalyear.GetFiscalYear(id);
            return View(fiscal);
        }

        public ActionResult Edit(int id)
        {
            var fiscal = _fiscalyear.GetFiscalYear(id);
            return View(fiscal);
        }


        [HttpPost]
        public ActionResult Edit(FiscalYearViewModel model)
        {
            if (ModelState.IsValid)
            {
                _fiscalyear.UpdateFiscalYear(model.Id, model);

                return RedirectToAction("GetAllRecords");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            _fiscalyear.DeleteFiscalYear(id);
            return RedirectToAction("GetAllRecords");
        }
    }
}

Library Project/Controllers/SubCategoryController.cs
using Library_Project.Interface;
using Library_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Project.Controllers
{
    [Authorize]
    public class SubCategoryController : Controller
    {
        private readonly ISubCategory _subcategory;
        public SubCategoryController(ISubCategory subcategory)
        {
            _subcategory = subcategory;
        }
        public ActionResult Create()
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.Where(x=>x.IsDelete==false).ToList(), "Id", "Name");
            }
            return View();

        }

        [HttpPost]
        public ActionResult Create(SubCategoryVIewModel model)
        {
            if (ModelState.IsValid)
            {
                int id = _subcategory.AddSubCategory(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.IsSuccess = "Data Added";
                return RedirectToAction("GetAllRecords");
                }
            }
            return View(model);
        }

        public ActionResult GetAllRecords()
        {
            var result = _subcategory.GetAllSubCategories();
            return View(result);
        }

        public ActionResult Details(int id)
        {
            var category = _subcategory.GetSubCategory(id);
            return View(category);
        }

        public ActionResult Edit(int id)
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.ToList(), "Id", "Name");
            }
            var category = _subcategory.GetSubCategory(id);
            return View(category);
        }


        [HttpPost]
        public ActionResult Edit(SubCategoryVIewModel model)
        {
            if (ModelState.IsValid)
            {
                _subcategory.UpdateSubCategory(model.Id, model);

                return RedirectToAction("GetAllRecords");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            _subcategory.DeleteSubCategory(id);
            return RedirectToAction("GetAllRecords");
        }
    }
}

Library Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>document Library</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Frontend/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/Frontend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Frontend/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Frontend/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Frontend/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Frontend/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Frontend/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Frontend/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/Frontend/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>

            </ul>

            <ul class="navbar-nav ml-auto">
               

                <!-- Messages Dropdown Menu -->
                <!-- Notifications Dropdown Menu -->
                @if (User.Identity.IsAuthenticated)
                {
                    <li><b>Hello</b> <br />@User.Identity.Name</li>

                    <li>

                     <a class="btn btn-primary" style="margin-left:10px;" href="@Url.Action("Logout","Account")">Log Out</a>
                    </li>
                }
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-white-primary elevation-4">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index","Home")" class="brand-link">
                <i class="fa-solid fa-book" style="font-size: 50px;"></i>
                <span class="brand-text" style="font-weight: bold;font-size:24px; color:black;">डकुमेण्ट लाईब्रेरी </span><hr />
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        

                        <li class="nav-item">
                            <a href="@Url.Action("GetAllRecords","Document")" class="nav-link">
                                <i class="fa-solid fa-gear"></i>
                                <p style="font-size:22px; font-weight:bold;">
                                    कागजातहरू
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("GetAllRecords","Category")" class="nav-link">
                                <i class="fa-solid fa-gear"></i>
                                <p style="font-size:22px; font-weight:bold;">

                                    कागजातको वर्ग
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("GetAllRecords","SubCategory")" class="nav-link">
                                <i class="fa-solid fa-gear"></i>
                                <p style="font-size:22px; font-weight:bold;">
                                    कागजातको उप-वर्ग
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("GetAllRecords","FiscalYear")" class="nav-link">
                                <i class="fa-solid fa-gear"></i>
                                <p style="font-size:22px; font-weight:bold;">
                                    आर्थिक बर्ष
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("GetAllRecords","DocumentType")" class="nav-link">
                                <i class="fa-solid fa-gear"></i>
                                <p style="font-size:22px; font-weight:bold;">
                                    कागजातको प्रकार
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("GetAllRecords","DocumentSource")" class="nav-link">
                                <i class="fa-solid fa-gear"></i>
                                <p style="font-size:22px; font-weight:bold;">
                                    कागजातको स्रोत
                                </p>
                            </a>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">

                    @RenderBody()
                    <!-- /.row (main row) -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer" style=" text-align:center">
            <strong>Copyright &copy; <a href="softechfoundation.com">Softtech Foundation</a>.</strong>
            All rights reserved.

        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/Frontend/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Frontend/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/Frontend/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Frontend/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/Frontend/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/Frontend/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Frontend/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Frontend/plugins/moment/moment.min.js"></script>
    <script src="~/Frontend/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Frontend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/Frontend/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Frontend/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Frontend/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Frontend/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Frontend/dist/js/pages/dashboard.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @RenderSection("scripts", required: false)
</body>
</html>